version: '3.8'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    working_dir: /usr/src/app
    ports:
      - 5173:5173
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true